baseURL = 'https://blog-23f.pages.dev/'
title = '乌漆嘛黑的学习笔记'
languageCode = "zh-CN"
relativeURLs = true
canonifyURLs = false
defaultContentLanguage = "zh"
theme = "paper"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[pagination]
  pagerSize = 8

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/post/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 30

[services]
  [services.disqus]
    # shortname = 'YOUR_DISQUS_SHORTNAME'     # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  description = '我与我周旋久，宁做我。'
  mainSections = ["post"]
  rss = true

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'wwenyue932-maker'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  # threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
  # bluesky = 'YOUR_BLUESKY_ID'               # https://bsky.app/profile/YOUR_BLUESKY_ID
  # rss = true                                # show rss icon

  # home page profile

  avatar = '/images/inco.jpg'                 # gravatar email or image url
  name = '乌漆嘛黑'
  bio = '我与我周旋久,宁做我'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  # monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
# graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "ltr"                         # RTL support for Right-to-left languages

  # giscus
# [params.giscus]
#   repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
#   repoId = 'YOUR_GISCUS_REPO_ID'
#   category = 'YOUR__GISCUS_CATEGORY'
#   categoryId = 'YOUR_GISCUS_CATEGORY_ID'
#   mapping = 'pathname'
#   theme = 'light'
#   lang = 'zh-CN'
